// Cognia Certification Exam — 100 multiple-choice questions covering all
// platform material: AI Overview, Intelligent Agents, Data Foundations,
// Machine Learning, Deep Learning, Reinforcement Learning, LLM, and AI Ethics.
// Each question is bilingual (id/en). `answer` is the 0-based index of the
// correct option. All original teaching content.
//
// Shape: { topic, id: { q, options:[4] }, en: { q, options:[4] }, answer }

export const certQuestions = [
  // ============ AI Overview (1–10) ============
  { topic: "AI Overview", answer: 0,
    id: { q: "Urutan dari yang paling luas ke paling sempit adalah…", options: ["AI → Machine Learning → Deep Learning", "Deep Learning → AI → Machine Learning", "Machine Learning → AI → Deep Learning", "LLM → AI → Deep Learning"] },
    en: { q: "The order from broadest to narrowest is…", options: ["AI → Machine Learning → Deep Learning", "Deep Learning → AI → Machine Learning", "Machine Learning → AI → Deep Learning", "LLM → AI → Deep Learning"] } },
  { topic: "AI Overview", answer: 1,
    id: { q: "Large Language Model (LLM) paling tepat digambarkan sebagai…", options: ["Sebuah basis data", "Penerapan deep learning untuk bahasa", "Algoritma clustering", "Perangkat keras GPU"] },
    en: { q: "An LLM is best described as…", options: ["A database", "A deep-learning application for language", "A clustering algorithm", "A GPU hardware device"] } },
  { topic: "AI Overview", answer: 2,
    id: { q: "Manakah pernyataan yang BENAR?", options: ["Semua AI adalah deep learning", "ML lebih luas daripada AI", "Tidak semua AI adalah machine learning", "AI dan LLM adalah sinonim"] },
    en: { q: "Which statement is TRUE?", options: ["All AI is deep learning", "ML is broader than AI", "Not all AI is machine learning", "AI and LLM are synonyms"] } },
  { topic: "AI Overview", answer: 3,
    id: { q: "Tiga faktor utama yang mendorong lonjakan AI dekade terakhir adalah…", options: ["Blockchain, IoT, 5G", "Cloud, mobile, sosmed", "VR, AR, metaverse", "Data melimpah, komputasi murah (GPU), algoritma matang"] },
    en: { q: "The three main drivers of AI's recent surge are…", options: ["Blockchain, IoT, 5G", "Cloud, mobile, social media", "VR, AR, metaverse", "Abundant data, cheap compute (GPU), mature algorithms"] } },
  { topic: "AI Overview", answer: 0,
    id: { q: "Sistem berbasis aturan (rule-based) yang tidak belajar dari data…", options: ["Tetap termasuk AI", "Bukan AI sama sekali", "Selalu deep learning", "Selalu lebih akurat dari ML"] },
    en: { q: "A rule-based system that does not learn from data…", options: ["Is still a form of AI", "Is not AI at all", "Is always deep learning", "Is always more accurate than ML"] } },
  { topic: "AI Overview", answer: 1,
    id: { q: "Untuk memfilter komentar kasar (klasifikasi teks), pendekatan yang wajar adalah…", options: ["Reinforcement learning", "Machine learning (klasifikasi)", "Rendering 3D", "Kompresi gambar"] },
    en: { q: "To filter toxic comments (text classification), a reasonable approach is…", options: ["Reinforcement learning", "Machine learning (classification)", "3D rendering", "Image compression"] } },
  { topic: "AI Overview", answer: 2,
    id: { q: "Deep Learning adalah bagian dari…", options: ["Statistika saja", "Basis data", "Machine Learning", "Sistem operasi"] },
    en: { q: "Deep Learning is a subset of…", options: ["Statistics only", "Databases", "Machine Learning", "Operating systems"] } },
  { topic: "AI Overview", answer: 0,
    id: { q: "Memperkirakan penjualan bulan depan dari data historis termasuk tugas…", options: ["Regresi/peramalan", "Clustering", "Klasifikasi gambar", "Enkripsi"] },
    en: { q: "Forecasting next month's sales from historical data is a…", options: ["Regression/forecasting task", "Clustering task", "Image classification task", "Encryption task"] } },
  { topic: "AI Overview", answer: 3,
    id: { q: "Manakah yang BUKAN sub-bidang AI yang dibahas di Cognia?", options: ["Machine Learning", "Deep Learning", "Reinforcement Learning", "Kriptografi kuantum"] },
    en: { q: "Which is NOT an AI subfield covered in Cognia?", options: ["Machine Learning", "Deep Learning", "Reinforcement Learning", "Quantum cryptography"] } },
  { topic: "AI Overview", answer: 1,
    id: { q: "Prinsip 'gunakan teknik sesuai masalah' bermakna…", options: ["Selalu pakai deep learning", "Pilih pendekatan paling cocok & hemat untuk masalahnya", "Selalu pakai LLM", "Hindari machine learning"] },
    en: { q: "The principle 'use the technique that fits the problem' means…", options: ["Always use deep learning", "Pick the most fitting & economical approach for the problem", "Always use an LLM", "Avoid machine learning"] } },

  // ============ Intelligent Agents (11–20) ============
  { topic: "Intelligent Agents", answer: 0,
    id: { q: "Sensor pada sebuah agen berfungsi untuk…", options: ["Menangkap keadaan lingkungan (persepsi)", "Menjalankan aksi", "Menyimpan kode", "Memberi reward"] },
    en: { q: "An agent's sensors are used to…", options: ["Perceive the environment's state", "Carry out actions", "Store code", "Give rewards"] } },
  { topic: "Intelligent Agents", answer: 1,
    id: { q: "Aktuator pada agen berfungsi untuk…", options: ["Menerima persepsi", "Menjalankan aksi ke lingkungan", "Menghitung loss", "Menyimpan memori"] },
    en: { q: "An agent's actuators are used to…", options: ["Receive percepts", "Carry out actions on the environment", "Compute loss", "Store memory"] } },
  { topic: "Intelligent Agents", answer: 2,
    id: { q: "Urutan siklus agen yang benar adalah…", options: ["Aksi → sensor → reward", "Program → memori → selesai", "Persepsi (sensor) → program agen → aksi (aktuator) → lingkungan berubah", "Lingkungan → aktuator → berhenti"] },
    en: { q: "The correct agent cycle is…", options: ["Action → sensor → reward", "Program → memory → done", "Perception (sensors) → agent program → action (actuators) → environment changes", "Environment → actuators → stop"] } },
  { topic: "Intelligent Agents", answer: 3,
    id: { q: "Lingkungan 'terobservasi sebagian' berarti…", options: ["Selalu deterministik", "Tidak ada agen lain", "Tidak pernah berubah", "Agen tidak dapat melihat seluruh keadaan sekaligus"] },
    en: { q: "A 'partially observable' environment means…", options: ["It is always deterministic", "There are no other agents", "It never changes", "The agent can't see the whole state at once"] } },
  { topic: "Intelligent Agents", answer: 0,
    id: { q: "Simple reflex agent memilih aksi berdasarkan…", options: ["Aturan kondisi–aksi atas persepsi saat ini", "Fungsi utilitas kompleks", "Pencarian mendalam", "Reward jangka panjang"] },
    en: { q: "A simple reflex agent chooses actions based on…", options: ["Condition–action rules on the current percept", "A complex utility function", "Deep search", "Long-term reward"] } },
  { topic: "Intelligent Agents", answer: 1,
    id: { q: "Agen berbasis model (model-based) menambahkan…", options: ["Fungsi utilitas", "Keadaan internal (memori) & model dunia", "Reward", "Jaringan saraf"] },
    en: { q: "A model-based agent adds…", options: ["A utility function", "Internal state (memory) & a world model", "Rewards", "A neural network"] } },
  { topic: "Intelligent Agents", answer: 2,
    id: { q: "Agen berbasis tujuan (goal-based) berbeda dari reflex karena…", options: ["Tidak butuh sensor", "Lebih lambat selalu", "Mempertimbangkan apakah aksi mendekatkan ke tujuan", "Tidak punya aktuator"] },
    en: { q: "A goal-based agent differs from reflex because it…", options: ["Needs no sensors", "Is always slower", "Considers whether actions move toward a goal", "Has no actuators"] } },
  { topic: "Intelligent Agents", answer: 3,
    id: { q: "Agen berbasis utilitas memilih aksi dengan…", options: ["Aturan if–then saja", "Reward acak", "Tujuan biner tercapai/tidak", "Utilitas harapan tertinggi (menimbang trade-off)"] },
    en: { q: "A utility-based agent chooses the action with…", options: ["Only if–then rules", "Random reward", "A binary reached/not goal", "Highest expected utility (weighing trade-offs)"] } },
  { topic: "Intelligent Agents", answer: 0,
    id: { q: "Learning agent memperbaiki dirinya dengan komponen…", options: ["Kritik, elemen belajar, generator masalah", "Hanya sensor", "Hanya aktuator", "Basis data statis"] },
    en: { q: "A learning agent improves itself via components…", options: ["Critic, learning element, problem generator", "Sensors only", "Actuators only", "A static database"] } },
  { topic: "Intelligent Agents", answer: 1,
    id: { q: "Catur (dengan lawan) adalah contoh lingkungan…", options: ["Agen tunggal", "Multi-agen (kompetitif)", "Tanpa aturan", "Kontinu"] },
    en: { q: "Chess (with an opponent) is an example of a … environment.", options: ["Single-agent", "Multi-agent (competitive)", "Rule-free", "Continuous"] } },

  // ============ Data Foundations (21–45) ============
  { topic: "Data Foundations", answer: 0,
    id: { q: "Langkah yang sering menyita waktu terbesar dalam proyek AI nyata adalah…", options: ["Pengumpulan & pembersihan data", "Memilih warna grafik", "Menulis judul laporan", "Membeli GPU"] },
    en: { q: "The step that often takes the most time in real AI projects is…", options: ["Data collection & cleaning", "Choosing chart colors", "Writing report titles", "Buying a GPU"] } },
  { topic: "Data Foundations", answer: 1,
    id: { q: "Data 'kontinu' contohnya…", options: ["Jenis kelamin", "Tinggi badan (172,5 cm)", "Warna mobil", "Status lulus/gagal"] },
    en: { q: "An example of 'continuous' data is…", options: ["Gender", "Height (172.5 cm)", "Car color", "Pass/fail status"] } },
  { topic: "Data Foundations", answer: 2,
    id: { q: "Data kategorikal NOMINAL adalah…", options: ["Rating buruk<sedang<baik", "Tingkat pendidikan", "Warna atau kota (tanpa urutan)", "Suhu"] },
    en: { q: "NOMINAL categorical data is…", options: ["Rating poor<fair<good", "Education level", "Color or city (no order)", "Temperature"] } },
  { topic: "Data Foundations", answer: 3,
    id: { q: "Data ORDINAL dicirikan oleh…", options: ["Tanpa urutan", "Selalu numerik kontinu", "Hanya dua nilai", "Kategori yang berurutan"] },
    en: { q: "ORDINAL data is characterized by…", options: ["No order", "Always continuous numeric", "Only two values", "Ordered categories"] } },
  { topic: "Data Foundations", answer: 0,
    id: { q: "Membersihkan data biasanya mencakup…", options: ["Menangani nilai kosong, duplikat, outlier, tipe salah", "Menambah GPU", "Mengubah tema situs", "Menghapus semua data"] },
    en: { q: "Data cleaning typically includes…", options: ["Handling missing values, duplicates, outliers, wrong types", "Adding GPUs", "Changing the site theme", "Deleting all data"] } },
  { topic: "Data Foundations", answer: 1,
    id: { q: "Imputasi nilai kosong dengan MEDIAN dipilih karena…", options: ["Selalu nol", "Tahan terhadap outlier dibanding mean", "Menghapus baris", "Mengacak data"] },
    en: { q: "Imputing missing values with the MEDIAN is chosen because it…", options: ["Is always zero", "Is robust to outliers vs the mean", "Deletes rows", "Randomizes data"] } },
  { topic: "Data Foundations", answer: 2,
    id: { q: "Min-Max scaling mengubah nilai menjadi rentang…", options: ["[-1, 1] selalu", "Rata-rata 0, std 1", "[0, 1]", "Bilangan bulat"] },
    en: { q: "Min-Max scaling maps values into the range…", options: ["Always [-1, 1]", "Mean 0, std 1", "[0, 1]", "Integers"] } },
  { topic: "Data Foundations", answer: 3,
    id: { q: "Standardisasi (Z-score) menghasilkan data dengan…", options: ["Rentang [0,1]", "Nilai bulat", "Median 0", "Rata-rata 0 dan standar deviasi 1"] },
    en: { q: "Standardization (Z-score) yields data with…", options: ["Range [0,1]", "Integer values", "Median 0", "Mean 0 and standard deviation 1"] } },
  { topic: "Data Foundations", answer: 0,
    id: { q: "One-hot encoding lebih tepat dari label encoding untuk data nominal karena…", options: ["Menghindari urutan palsu antar kategori", "Selalu lebih sedikit kolom", "Mengubah angka jadi teks", "Menghapus kategori"] },
    en: { q: "One-hot encoding beats label encoding for nominal data because it…", options: ["Avoids a fake order between categories", "Always uses fewer columns", "Turns numbers into text", "Removes categories"] } },
  { topic: "Data Foundations", answer: 1,
    id: { q: "Risiko label encoding pada data nominal adalah…", options: ["Terlalu banyak kolom", "Model mengira ada urutan/peringkat palsu", "Tidak bisa dihitung", "Menghapus data"] },
    en: { q: "The risk of label encoding on nominal data is…", options: ["Too many columns", "The model assumes a fake order/ranking", "It can't be computed", "It deletes data"] } },
  { topic: "Data Foundations", answer: 2,
    id: { q: "Tujuan membagi data menjadi train/validation/test adalah…", options: ["Mempercepat GPU", "Menghapus outlier", "Menilai model pada data yang belum pernah dilihat", "Menambah jumlah data"] },
    en: { q: "The purpose of splitting data into train/validation/test is…", options: ["To speed up the GPU", "To remove outliers", "To judge the model on unseen data", "To increase the data size"] } },
  { topic: "Data Foundations", answer: 3,
    id: { q: "Data uji (test set) sebaiknya…", options: ["Dipakai untuk melatih model", "Dipakai menyetel hyperparameter", "Dibuang", "Dikunci sampai akhir & dipakai sekali"] },
    en: { q: "The test set should be…", options: ["Used to train the model", "Used to tune hyperparameters", "Discarded", "Locked until the end & used once"] } },
  { topic: "Data Foundations", answer: 0,
    id: { q: "Kebocoran data (data leakage) terjadi bila…", options: ["Informasi dari test ikut memengaruhi pelatihan", "Data terlalu banyak", "Model terlalu kecil", "GPU terlalu cepat"] },
    en: { q: "Data leakage happens when…", options: ["Test information influences training", "There is too much data", "The model is too small", "The GPU is too fast"] } },
  { topic: "Data Foundations", answer: 1,
    id: { q: "Cara benar menghitung parameter penskalaan (mean/std) adalah…", options: ["Dari seluruh data lalu dibagi", "Dari data latih saja, lalu diterapkan ke test", "Dari data test saja", "Diacak"] },
    en: { q: "The correct way to compute scaling parameters (mean/std) is…", options: ["From all data then split", "From training data only, then apply to test", "From the test set only", "Randomly"] } },
  { topic: "Data Foundations", answer: 2,
    id: { q: "Histogram berguna untuk melihat…", options: ["Korelasi dua fitur", "Kode program", "Sebaran (distribusi) sebuah fitur", "Kecepatan GPU"] },
    en: { q: "A histogram is useful for seeing…", options: ["Correlation of two features", "Program code", "The distribution of a feature", "GPU speed"] } },
  { topic: "Data Foundations", answer: 3,
    id: { q: "Koefisien korelasi mendekati +1 menandakan…", options: ["Tidak ada hubungan", "Hubungan negatif kuat", "Data hilang", "Hubungan positif kuat"] },
    en: { q: "A correlation near +1 indicates…", options: ["No relationship", "A strong negative relationship", "Missing data", "A strong positive relationship"] } },
  { topic: "Data Foundations", answer: 0,
    id: { q: "Boxplot menandai OUTLIER menggunakan aturan umum…", options: ["Di luar 1,5×IQR dari Q1/Q3", "Di atas rata-rata", "Nilai genap", "Nilai teratas saja"] },
    en: { q: "A boxplot marks OUTLIERS using the common rule…", options: ["Beyond 1.5×IQR from Q1/Q3", "Above the mean", "Even values", "Only the top value"] } },
  { topic: "Data Foundations", answer: 1,
    id: { q: "OVERFITTING terjadi ketika model…", options: ["Terlalu sederhana", "Menghafal noise data latih & buruk di data baru", "Selalu akurat", "Tidak punya parameter"] },
    en: { q: "OVERFITTING happens when a model…", options: ["Is too simple", "Memorizes training noise & does poorly on new data", "Is always accurate", "Has no parameters"] } },
  { topic: "Data Foundations", answer: 2,
    id: { q: "UNDERFITTING terjadi ketika model…", options: ["Menghafal data latih", "Sempurna di test", "Terlalu sederhana untuk menangkap pola", "Terlalu kompleks"] },
    en: { q: "UNDERFITTING happens when a model…", options: ["Memorizes training data", "Is perfect on test", "Is too simple to capture the pattern", "Is too complex"] } },
  { topic: "Data Foundations", answer: 3,
    id: { q: "Tanda khas overfitting adalah…", options: ["Error latih & test sama tinggi", "Error latih tinggi", "Tidak ada error", "Error latih rendah tapi error test tinggi"] },
    en: { q: "A hallmark of overfitting is…", options: ["Train & test error equally high", "High train error", "No error", "Low train error but high test error"] } },
  { topic: "Data Foundations", answer: 0,
    id: { q: "Feature engineering adalah…", options: ["Membuat/mengubah fitur agar lebih informatif", "Membeli server", "Menghapus model", "Menulis dokumentasi"] },
    en: { q: "Feature engineering is…", options: ["Creating/transforming features to be more informative", "Buying servers", "Deleting the model", "Writing documentation"] } },
  { topic: "Data Foundations", answer: 1,
    id: { q: "PCA umumnya dipakai untuk…", options: ["Menambah fitur", "Reduksi dimensi sambil menjaga struktur penting", "Enkripsi", "Melatih LLM"] },
    en: { q: "PCA is generally used for…", options: ["Adding features", "Dimensionality reduction while keeping key structure", "Encryption", "Training LLMs"] } },
  { topic: "Data Foundations", answer: 2,
    id: { q: "Data deret waktu (time series) penting menjaga…", options: ["Warna", "Ukuran file", "Urutan menurut waktu", "Nama kolom"] },
    en: { q: "Time-series data must preserve…", options: ["Color", "File size", "Order by time", "Column names"] } },
  { topic: "Data Foundations", answer: 3,
    id: { q: "Data teks untuk model biasanya perlu…", options: ["Dihapus", "Dijadikan gambar", "Dibiarkan mentah", "Tokenisasi & embedding"] },
    en: { q: "Text data for a model usually needs…", options: ["To be deleted", "To be turned into images", "To be left raw", "Tokenization & embedding"] } },
  { topic: "Data Foundations", answer: 0,
    id: { q: "Pemantauan model setelah deploy penting karena…", options: ["Performa bisa menurun (data drift)", "Model tak pernah salah", "GPU jadi lebih murah", "Data selalu tetap"] },
    en: { q: "Monitoring a model after deployment matters because…", options: ["Performance can degrade (data drift)", "The model is never wrong", "GPUs get cheaper", "Data is always constant"] } },

  // ============ Machine Learning (46–60) ============
  { topic: "Machine Learning", answer: 0,
    id: { q: "Supervised learning membutuhkan…", options: ["Data berlabel (input + jawaban)", "Tidak ada data", "Hanya reward", "Hanya gambar"] },
    en: { q: "Supervised learning requires…", options: ["Labeled data (input + answers)", "No data", "Only rewards", "Only images"] } },
  { topic: "Machine Learning", answer: 1,
    id: { q: "Unsupervised learning bertujuan…", options: ["Memprediksi label", "Menemukan struktur/kelompok tanpa label", "Memaksimalkan reward", "Mengenkripsi data"] },
    en: { q: "Unsupervised learning aims to…", options: ["Predict labels", "Find structure/groups without labels", "Maximize reward", "Encrypt data"] } },
  { topic: "Machine Learning", answer: 2,
    id: { q: "k-NN mengklasifikasikan titik baru berdasarkan…", options: ["Nilai rata-rata semua data", "Sebuah garis lurus", "Mayoritas kelas k tetangga terdekat", "Reward"] },
    en: { q: "k-NN classifies a new point by…", options: ["The mean of all data", "A straight line", "The majority class among k nearest neighbors", "Reward"] } },
  { topic: "Machine Learning", answer: 3,
    id: { q: "k-Means adalah algoritma…", options: ["Supervised klasifikasi", "Regresi linear", "Reinforcement", "Clustering (unsupervised)"] },
    en: { q: "k-Means is a … algorithm.", options: ["Supervised classification", "Linear regression", "Reinforcement", "Clustering (unsupervised)"] } },
  { topic: "Machine Learning", answer: 0,
    id: { q: "Regresi linear mencari…", options: ["Garis terbaik y = m·x + b", "Kelas mayoritas", "Cluster", "Policy"] },
    en: { q: "Linear regression finds…", options: ["The best line y = m·x + b", "The majority class", "Clusters", "A policy"] } },
  { topic: "Machine Learning", answer: 1,
    id: { q: "Regresi logistik memakai fungsi … untuk probabilitas.", options: ["Linear", "Sigmoid", "ReLU", "Sinus"] },
    en: { q: "Logistic regression uses the … function for probability.", options: ["Linear", "Sigmoid", "ReLU", "Sine"] } },
  { topic: "Machine Learning", answer: 2,
    id: { q: "Decision tree membagi data dengan…", options: ["Sigmoid", "Reward", "Serangkaian pertanyaan/split fitur", "Konvolusi"] },
    en: { q: "A decision tree splits data with…", options: ["A sigmoid", "Rewards", "A series of feature questions/splits", "Convolutions"] } },
  { topic: "Machine Learning", answer: 3,
    id: { q: "Segmentasi pelanggan tanpa kategori awal adalah contoh…", options: ["Regresi", "Klasifikasi", "Reinforcement", "Clustering unsupervised"] },
    en: { q: "Customer segmentation with no prior categories is an example of…", options: ["Regression", "Classification", "Reinforcement", "Unsupervised clustering"] } },
  { topic: "Machine Learning", answer: 0,
    id: { q: "Pada k-NN, memperbesar k umumnya membuat batas keputusan…", options: ["Lebih halus", "Lebih tajam/berombak", "Hilang", "Acak"] },
    en: { q: "In k-NN, increasing k generally makes the decision boundary…", options: ["Smoother", "Sharper/noisier", "Disappear", "Random"] } },
  { topic: "Machine Learning", answer: 1,
    id: { q: "Deteksi email spam (label spam/bukan) adalah tugas…", options: ["Clustering", "Klasifikasi (supervised)", "Regresi kontinu", "Reinforcement"] },
    en: { q: "Spam detection (spam/not labels) is a…", options: ["Clustering task", "Classification (supervised) task", "Continuous regression task", "Reinforcement task"] } },
  { topic: "Machine Learning", answer: 2,
    id: { q: "Naive Bayes mengasumsikan fitur…", options: ["Selalu numerik", "Berurutan", "Saling independen", "Berkorelasi kuat"] },
    en: { q: "Naive Bayes assumes features are…", options: ["Always numeric", "Ordered", "Mutually independent", "Strongly correlated"] } },
  { topic: "Machine Learning", answer: 3,
    id: { q: "Kualitas regresi linear sering diukur dengan…", options: ["Akurasi", "F1", "Silhouette", "MSE"] },
    en: { q: "Linear regression quality is often measured by…", options: ["Accuracy", "F1", "Silhouette", "MSE"] } },
  { topic: "Machine Learning", answer: 0,
    id: { q: "Random forest adalah…", options: ["Kumpulan banyak decision tree", "Satu neuron", "Algoritma clustering", "Fungsi aktivasi"] },
    en: { q: "A random forest is…", options: ["An ensemble of many decision trees", "A single neuron", "A clustering algorithm", "An activation function"] } },
  { topic: "Machine Learning", answer: 1,
    id: { q: "Model 'belajar pola dari data' disebut…", options: ["Basis data", "Model", "Kompilator", "Server"] },
    en: { q: "The thing that 'learns patterns from data' is called a…", options: ["Database", "Model", "Compiler", "Server"] } },
  { topic: "Machine Learning", answer: 2,
    id: { q: "Ambang 0,5 pada regresi logistik dipakai untuk…", options: ["Menghitung mean", "Menormalkan data", "Menentukan kelas dari probabilitas", "Mengacak bobot"] },
    en: { q: "A 0.5 threshold in logistic regression is used to…", options: ["Compute the mean", "Normalize data", "Decide the class from a probability", "Randomize weights"] } },

  // ============ Deep Learning (61–72) ============
  { topic: "Deep Learning", answer: 0,
    id: { q: "Deep learning menggunakan…", options: ["Neural network berlapis banyak", "Hanya pohon keputusan", "Hanya k-means", "Hanya aturan if–then"] },
    en: { q: "Deep learning uses…", options: ["Many-layered neural networks", "Only decision trees", "Only k-means", "Only if–then rules"] } },
  { topic: "Deep Learning", answer: 1,
    id: { q: "CNN paling cocok untuk data…", options: ["Tabel angka", "Gambar", "Hanya teks pendek", "Reward"] },
    en: { q: "CNNs are best suited for … data.", options: ["Numeric tables", "Images", "Only short text", "Reward"] } },
  { topic: "Deep Learning", answer: 2,
    id: { q: "Backpropagation berfungsi untuk…", options: ["Menggambar grafik", "Menghapus data", "Menyesuaikan bobot untuk mengecilkan loss", "Mengenkripsi model"] },
    en: { q: "Backpropagation is used to…", options: ["Draw charts", "Delete data", "Adjust weights to reduce loss", "Encrypt the model"] } },
  { topic: "Deep Learning", answer: 3,
    id: { q: "Fungsi aktivasi memberi jaringan kemampuan…", options: ["Menghapus neuron", "Menghemat listrik", "Menyimpan data", "Menangkap pola non-linear"] },
    en: { q: "Activation functions give a network the ability to…", options: ["Delete neurons", "Save power", "Store data", "Capture non-linear patterns"] } },
  { topic: "Deep Learning", answer: 0,
    id: { q: "ReLU dikenal karena…", options: ["Cepat & sederhana", "Selalu output negatif", "Membatasi ke [0,1]", "Menghitung korelasi"] },
    en: { q: "ReLU is known for being…", options: ["Fast & simple", "Always negative output", "Bounding to [0,1]", "Computing correlation"] } },
  { topic: "Deep Learning", answer: 1,
    id: { q: "Kernel/filter pada CNN…", options: ["Menghapus piksel", "Digeser ke seluruh gambar untuk mendeteksi fitur", "Menghitung reward", "Mengurutkan data"] },
    en: { q: "A CNN kernel/filter…", options: ["Deletes pixels", "Slides across the image to detect features", "Computes reward", "Sorts data"] } },
  { topic: "Deep Learning", answer: 2,
    id: { q: "Transformer/RNN cocok untuk data…", options: ["Hanya gambar statis", "Hanya tabel", "Berurutan (sekuensial) seperti teks", "Reward"] },
    en: { q: "Transformers/RNNs suit … data.", options: ["Only static images", "Only tables", "Sequential data like text", "Reward"] } },
  { topic: "Deep Learning", answer: 3,
    id: { q: "Loss yang mengecil selama pelatihan menandakan…", options: ["Model rusak", "Data hilang", "GPU mati", "Model makin cocok dengan data latih"] },
    en: { q: "A shrinking loss during training indicates…", options: ["The model is broken", "Data is lost", "The GPU is off", "The model fits the training data better"] } },
  { topic: "Deep Learning", answer: 0,
    id: { q: "Deteksi tepi (edge detection) memakai operator seperti…", options: ["Sobel (gradien)", "Sigmoid", "k-means", "Softmax saja"] },
    en: { q: "Edge detection uses operators like…", options: ["Sobel (gradients)", "Sigmoid", "k-means", "Softmax only"] } },
  { topic: "Deep Learning", answer: 1,
    id: { q: "Pengenalan tulisan tangan (MNIST) adalah contoh tugas…", options: ["Clustering", "Klasifikasi gambar", "Regresi harga", "Reinforcement"] },
    en: { q: "Handwriting recognition (MNIST) is an example of…", options: ["Clustering", "Image classification", "Price regression", "Reinforcement"] } },
  { topic: "Deep Learning", answer: 2,
    id: { q: "Neuron pada hidden layer menerapkan…", options: ["Hanya penjumlahan linear", "Hanya penyimpanan", "Jumlah berbobot + fungsi aktivasi non-linear", "Enkripsi"] },
    en: { q: "A hidden-layer neuron applies…", options: ["Only a linear sum", "Only storage", "A weighted sum + a non-linear activation", "Encryption"] } },
  { topic: "Deep Learning", answer: 3,
    id: { q: "'Deep' pada deep learning merujuk pada…", options: ["Kedalaman air", "Ukuran data", "Kecepatan GPU", "Banyaknya lapisan (layer)"] },
    en: { q: "'Deep' in deep learning refers to…", options: ["Water depth", "Data size", "GPU speed", "The number of layers"] } },

  // ============ Reinforcement Learning (73–84) ============
  { topic: "Reinforcement Learning", answer: 0,
    id: { q: "RL berpusat pada…", options: ["Agen yang belajar dari reward atas aksinya", "Data berlabel", "Clustering", "Enkripsi"] },
    en: { q: "RL centers on…", options: ["An agent learning from rewards for its actions", "Labeled data", "Clustering", "Encryption"] } },
  { topic: "Reinforcement Learning", answer: 1,
    id: { q: "Dalam RL, 'state' adalah…", options: ["Reward total", "Kondisi lingkungan saat ini", "Strategi", "Fungsi loss"] },
    en: { q: "In RL, a 'state' is…", options: ["Total reward", "The current situation of the environment", "A strategy", "A loss function"] } },
  { topic: "Reinforcement Learning", answer: 2,
    id: { q: "'Policy' dalam RL berarti…", options: ["Kumpulan data", "Reward", "Strategi memilih aksi", "Sensor"] },
    en: { q: "A 'policy' in RL is…", options: ["A dataset", "A reward", "The strategy for choosing actions", "A sensor"] } },
  { topic: "Reinforcement Learning", answer: 3,
    id: { q: "Reward dalam RL adalah…", options: ["Kode program", "Jumlah fitur", "Bobot model", "Umpan balik dari lingkungan atas aksi"] },
    en: { q: "A reward in RL is…", options: ["Program code", "The number of features", "Model weights", "Feedback from the environment for an action"] } },
  { topic: "Reinforcement Learning", answer: 0,
    id: { q: "Trade-off eksplorasi vs eksploitasi berarti…", options: ["Coba hal baru vs pakai yang terbaik diketahui", "Latih vs uji", "Simpan vs hapus", "Enkripsi vs dekripsi"] },
    en: { q: "The explore vs exploit trade-off means…", options: ["Try new things vs use the best known", "Train vs test", "Save vs delete", "Encrypt vs decrypt"] } },
  { topic: "Reinforcement Learning", answer: 1,
    id: { q: "ε-greedy dengan ε kecil cenderung…", options: ["Terlalu banyak eksplorasi", "Kurang eksplorasi (bisa terjebak)", "Selalu optimal", "Mengabaikan reward"] },
    en: { q: "ε-greedy with small ε tends to…", options: ["Over-explore", "Under-explore (can get stuck)", "Always be optimal", "Ignore reward"] } },
  { topic: "Reinforcement Learning", answer: 2,
    id: { q: "Q-learning memperbarui…", options: ["Bobot CNN", "Cluster", "Nilai (state, action)", "Korelasi"] },
    en: { q: "Q-learning updates…", options: ["CNN weights", "Clusters", "(state, action) values", "Correlations"] } },
  { topic: "Reinforcement Learning", answer: 3,
    id: { q: "Contoh penerapan RL yang tepat adalah…", options: ["Enkripsi file", "Membersihkan data", "Menghitung rata-rata", "Navigasi robot / permainan / optimasi rute"] },
    en: { q: "A fitting RL application is…", options: ["File encryption", "Data cleaning", "Computing an average", "Robot navigation / games / route optimization"] } },
  { topic: "Reinforcement Learning", answer: 0,
    id: { q: "RL dibangun di atas konsep…", options: ["Agen & lingkungan", "Basis data relasional", "Kompilator", "Enkripsi"] },
    en: { q: "RL is built on the concept of…", options: ["Agent & environment", "Relational databases", "Compilers", "Encryption"] } },
  { topic: "Reinforcement Learning", answer: 1,
    id: { q: "Faktor diskon (γ) mengendalikan…", options: ["Kecepatan GPU", "Seberapa penting reward masa depan", "Jumlah fitur", "Ukuran gambar"] },
    en: { q: "The discount factor (γ) controls…", options: ["GPU speed", "How much future rewards matter", "The number of features", "Image size"] } },
  { topic: "Reinforcement Learning", answer: 2,
    id: { q: "Multi-armed bandit adalah kerangka untuk…", options: ["Klasifikasi gambar", "Regresi", "Menyeimbangkan eksplorasi–eksploitasi", "Tokenisasi"] },
    en: { q: "The multi-armed bandit is a framework for…", options: ["Image classification", "Regression", "Balancing exploration–exploitation", "Tokenization"] } },
  { topic: "Reinforcement Learning", answer: 3,
    id: { q: "CartPole (menyeimbangkan tiang) adalah contoh tugas…", options: ["Clustering", "Klasifikasi teks", "Regresi", "Kontrol berbasis RL"] },
    en: { q: "CartPole (balancing a pole) is an example of a…", options: ["Clustering task", "Text classification task", "Regression task", "RL-based control task"] } },

  // ============ LLM (85–92) ============
  { topic: "LLM", answer: 0,
    id: { q: "Tugas dasar pelatihan LLM adalah…", options: ["Memprediksi token (kata) berikutnya", "Mengelompokkan gambar", "Menghitung reward", "Mengenkripsi teks"] },
    en: { q: "An LLM's basic training task is…", options: ["Predicting the next token (word)", "Clustering images", "Computing rewards", "Encrypting text"] } },
  { topic: "LLM", answer: 1,
    id: { q: "'Token' pada LLM adalah…", options: ["Kunci keamanan", "Potongan kata yang diproses model", "Reward", "Lapisan CNN"] },
    en: { q: "A 'token' in an LLM is…", options: ["A security key", "A chunk of words the model processes", "A reward", "A CNN layer"] } },
  { topic: "LLM", answer: 2,
    id: { q: "Mekanisme 'attention' berfungsi…", options: ["Menghapus kata", "Mengenkripsi teks", "Menimbang kata mana yang penting", "Menghitung MSE"] },
    en: { q: "The 'attention' mechanism…", options: ["Deletes words", "Encrypts text", "Weighs which words matter", "Computes MSE"] } },
  { topic: "LLM", answer: 3,
    id: { q: "Urutan pelatihan LLM yang umum adalah…", options: ["Deploy lalu latih", "Uji lalu hapus", "Clustering lalu regresi", "Pre-training lalu fine-tuning"] },
    en: { q: "A common LLM training sequence is…", options: ["Deploy then train", "Test then delete", "Clustering then regression", "Pre-training then fine-tuning"] } },
  { topic: "LLM", answer: 0,
    id: { q: "'Prompt' adalah…", options: ["Instruksi yang kita berikan ke model", "Bobot model", "Fungsi loss", "Dataset uji"] },
    en: { q: "A 'prompt' is…", options: ["The instruction we give the model", "Model weights", "A loss function", "A test dataset"] } },
  { topic: "LLM", answer: 1,
    id: { q: "'Halusinasi' pada LLM berarti…", options: ["Model berhenti bekerja", "Model mengarang fakta yang salah dengan percaya diri", "Model terlalu lambat", "Model kehabisan token"] },
    en: { q: "'Hallucination' in an LLM means…", options: ["The model stops working", "The model confidently makes up false facts", "The model is too slow", "The model runs out of tokens"] } },
  { topic: "LLM", answer: 2,
    id: { q: "LLM berbasis arsitektur…", options: ["Decision tree", "k-means", "Transformer", "Sobel"] },
    en: { q: "LLMs are based on the … architecture.", options: ["Decision tree", "k-means", "Transformer", "Sobel"] } },
  { topic: "LLM", answer: 3,
    id: { q: "Batasan LLM yang perlu diingat adalah…", options: ["Tak butuh data", "Selalu benar", "Tak sensitif pada cara bertanya", "Hanya tahu hingga batas data pelatihan & bisa keliru"] },
    en: { q: "An LLM limitation to remember is…", options: ["It needs no data", "It is always right", "It's insensitive to phrasing", "It only knows up to its training cutoff & can be wrong"] } },

  // ============ AI Ethics (93–100) ============
  { topic: "AI Ethics", answer: 0,
    id: { q: "Bias algoritmik sering berakar dari…", options: ["Data historis yang timpang", "GPU cepat", "Terlalu sedikit warna", "Kode yang rapi"] },
    en: { q: "Algorithmic bias often stems from…", options: ["Skewed historical data", "Fast GPUs", "Too few colors", "Clean code"] } },
  { topic: "AI Ethics", answer: 1,
    id: { q: "Menghapus label ras/gender saja sering tidak cukup karena…", options: ["Data jadi kosong", "Fitur proksi (mis. kode pos) masih membocorkannya", "Model mati", "Akurasi jadi 100%"] },
    en: { q: "Removing the race/gender label alone is often not enough because…", options: ["Data becomes empty", "Proxy features (e.g. zip code) still leak it", "The model dies", "Accuracy becomes 100%"] } },
  { topic: "AI Ethics", answer: 2,
    id: { q: "Prompt injection adalah serangan…", options: ["Pada listrik server", "Pada layar", "Menyisipkan perintah tersembunyi agar AI melanggar aturannya", "Pada baterai"] },
    en: { q: "Prompt injection is an attack that…", options: ["Targets server power", "Targets the screen", "Hides commands to make the AI break its rules", "Targets the battery"] } },
  { topic: "AI Ethics", answer: 3,
    id: { q: "Data poisoning adalah…", options: ["Membersihkan data", "Menormalkan data", "Membagi data", "Menyisipkan contoh jahat ke data latih"] },
    en: { q: "Data poisoning is…", options: ["Cleaning data", "Normalizing data", "Splitting data", "Injecting malicious examples into training data"] } },
  { topic: "AI Ethics", answer: 0,
    id: { q: "Prinsip 'human-in-the-loop' menekankan…", options: ["Manusia tetap mengendalikan keputusan berisiko tinggi", "Otomasi penuh selalu", "Menghapus manusia", "Mengabaikan audit"] },
    en: { q: "The 'human-in-the-loop' principle stresses…", options: ["Humans stay in control of high-stakes decisions", "Always full automation", "Removing humans", "Ignoring audits"] } },
  { topic: "AI Ethics", answer: 1,
    id: { q: "Semakin tinggi risiko sebuah penggunaan AI, maka…", options: ["Semakin sedikit pengawasan", "Semakin besar kendali/pengawasan manusia yang wajib", "Semakin cepat GPU", "Semakin murah"] },
    en: { q: "The higher the risk of an AI use…", options: ["The less oversight is needed", "The more human control/oversight is required", "The faster the GPU", "The cheaper it is"] } },
  { topic: "AI Ethics", answer: 2,
    id: { q: "Contoh adversarial pada computer vision dapat…", options: ["Mempercepat model", "Menghemat data", "Menipu model mengenali objek dengan salah", "Menambah akurasi"] },
    en: { q: "Adversarial examples in computer vision can…", options: ["Speed up the model", "Save data", "Fool the model into misrecognizing objects", "Increase accuracy"] } },
  { topic: "AI Ethics", answer: 3,
    id: { q: "Di Indonesia, perlindungan data pribadi diatur terutama oleh…", options: ["UU Hak Cipta", "UU Lalu Lintas", "UU ITE saja", "UU Pelindungan Data Pribadi (PDP) No. 27/2022"] },
    en: { q: "In Indonesia, personal-data protection is primarily governed by…", options: ["The Copyright Law", "The Traffic Law", "The ITE Law only", "The Personal Data Protection Law (UU PDP) No. 27/2022"] } },
];

export const CERT_TOTAL = certQuestions.length; // 100
